# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEmision', models.DateField()),
                ('ciudadO', models.CharField(choices=[('Esmeraldas', 'Esmeraldas'), ('Manabi', 'Manabi'), ('Quito', 'Quito'), ('Guayaquil', 'Guayaquil'), ('Latacunga', 'Latacunga')], default='Guayaquil', max_length=10)),
                ('ciudadD', models.CharField(choices=[('Esmeraldas', 'Esmeraldas'), ('Manabi', 'Manabi'), ('Quito', 'Quito'), ('Guayaquil', 'Guayaquil'), ('Latacunga', 'Latacunga')], default='Guayaquil', max_length=10)),
                ('precio', models.FloatField()),
                ('cedula', models.CharField(max_length=10)),
                ('puesto', models.CharField(max_length=3)),
            ],
        ),
    ]
